### ISSUE TITLE
generating models with different poly-count 

### ISSUE THREAD

**Issue by wofsauge** [deep-geometry/abc-dataset#5]
Hi,
i want to try to train a GCN to estimate a Low-Polygon version of an Object, using the ABC-Dataset. For that i need to convert the objects from the datasets to a lower resolution, since the provided mesh files are all in a very high resolution. In the paper, there was a section where you had the same model but with 3 different vertex densities (as seen in the screenshot marked in red). 
How can i generate those? did you used a special tool to create those? if yes, where can i find that? 
![Unbenannt](https://user-images.githubusercontent.com/245725/60576210-483de700-9d7d-11e9-8544-d586805e142a.png)

**Comment by skoch9** [comment]
Hi,
for this we are using a slightly modified version of the [qslim algorithm](https://people.eecs.berkeley.edu/~jrs/meshpapers/GarlandHeckbert2.pdf) implementation in [libigl](https://github.com/libigl/libigl/blob/master/include/igl/qslim.h). 

You could start with the [mesh decimation example](https://github.com/libigl/libigl/blob/master/tutorial/703_Decimation/main.cpp) of libigl, which is basic decimation but should run out of the box and then modify it to use the qslim function instead of the simple decimation.

**Comment by wofsauge** [comment]
Thank you very much for your answer! 
It was pretty simple to change the mesh decimation example to use qslim and it works pretty well. 

Here is my code, if some future people want to do the same task: https://pastebin.com/7Gf86eWc
